version: '2'

services:
  site:
    build: .
    image: physicsdemos
    container_name: physicsdemos
    ports:
      - "80:80"
    volumes:
      - ./site:/site
      - ./apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
